# Generated by Django 5.2.15 on 2026-06-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_food_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_details',
            name='price',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
