# Generated by Django 5.2.15 on 2026-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_food_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_details',
            name='category',
            field=models.CharField(default='burgers', max_length=50),
        ),
    ]
