# Generated by Django 5.2.15 on 2026-06-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_food_details_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_details',
            name='category',
        ),
    ]
