# Generated by Django 5.2.15 on 2026-06-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0006_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_details',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
