# Generated by Django 5.2.15 on 2026-06-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0009_user_management_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('building_no', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('shipping_address', models.CharField(max_length=100)),
                ('FOOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.food_details')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.user_management_table')),
            ],
        ),
    ]
